### ISSUE TITLE
Fishing not levelling as of 2.1.2 (Minecraft 1.16.1)

### ISSUE THREAD

**Issue by bananabenana** [SilverAndro/RPGStats#10]
So all stats work, except fishing. Can't gather fishing experience.
Is this fixed in the newest version? Also, if I update to the newest version will players on the server lose their progress?

Thanks

**Comment by bananabenana** [comment]
Funnily enough, 2.1.3 does work in 1.16.1. 

> I haven't considered people would still be on 1.16.1 forgetting mojang broke most worldgen.

No I haven't upgraded because getting my users on the server to upgrade is a pain. 
Has 1.16.2 fixed worldgen?

Again, thanks for your help!

**Comment by P03W** [comment]
2.1.3 only _mostly_ works in 1.16.1

I expect using bone meal will cause issues if not an instant crash

Also 1.16.2 redid almost all worldgen and biome code so alot of.mlds that used those are having trouble updating

**Comment by P03W** [comment]
If your still on 1.16.1, I just backported a fix for this

**Comment by bananabenana** [comment]
Oh, far out. What a champ.
Much appreciated.
