### ISSUE TITLE
Mod for version 1.16.5/1.18.2 can't be found in Curseforge Launcher

### ISSUE THREAD

**Issue by PhoenixEvolver** [SilverAndro/RPGStats#106]
**Describe the bug**

**To Reproduce**
1. Open Curseforge launcher
2. Create a custom profile/Click on an existing one.
3. Click "Add More Content"
4. Search "RPGStats", "Stats" or "RPG"

**Expected behavior**
The mod shows up on the Curseforge launcher

**Screenshots and Logs**
![Level up everything](https://user-images.githubusercontent.com/67493734/174423130-c8f24bc6-3e9a-4996-8f12-fa2dc1c10fbd.png)

**Comment by SilverAndro** [comment]
I have no idea how the curseforge client works so not sure I can be of much help

You are looking under fabric mods, right?

**Comment by PhoenixEvolver** [comment]
I just clicked on the "Install with Curseforge app" and saw that it's incompatible with the current mod loader. 
Using Forge 36.2.25
"e" profile is using Forge 40.1.0
My bad.
![Penguin](https://user-images.githubusercontent.com/67493734/174423261-9bf79b19-bc95-4957-9246-90e074650141.png)

**Comment by PhoenixEvolver** [comment]
Wait, it's a Fabric mod?

**Comment by Jamalam360** [comment]
Yes
