### ISSUE TITLE
Port to 1.19

### ISSUE THREAD

**Issue by CamperSamu** [SilverAndro/RPGStats#107]

**Comment by SilverAndro** [comment]
Im on it im on it hahaha 😅 

Lifes been busy recently

**Comment by CamperSamu** [comment]
I'm in the same spot but I wanted to report this on the mods I care the most so when I can I contribute and close the issue!

**Comment by SilverAndro** [comment]
Fair enough!

**Comment by CamperSamu** [comment]
Thanks for the update!
I would've liked to contribute to it but I am way too busy now

**Comment by SilverAndro** [comment]
I have discovered a critical error :D

**Comment by SilverAndro** [comment]
Properly updated in 4.3.15 😅
