### ISSUE TITLE
[Suggestion] Change the name of the magic stat to "alchemy"

### ISSUE THREAD

**Issue by elhertz** [SilverAndro/RPGStats#111]
I don't think naming this stat "magic" makes sense and that it should be named "alchemy " instead.

**Comment by SilverAndro** [comment]
Perhaps, but leaving it as "magic" leaves it more generalized for support, so im not inclined to change it to be even more specific

(Although this is giving me the idea to expand how to get it, such as totems of undying *also* giving some magic xp)

**Comment by elhertz** [comment]
Potions and totems sound like "witchcraft" to me. 
"Magic" does make sense though. 
You can go ahead an close this issue if you want. Thanks!
