### ISSUE TITLE
Arrows have bad accuracy with Ranged level over 50

### ISSUE THREAD

**Issue by HyperSoop** [SilverAndro/RPGStats#113]
**Describe the bug**
Arrows fired by someone of Ranged level over 50 are so accurate they are actually less accurate than they should be.

**To Reproduce**
1. Cap the max level for skills over 50
2. Cheat your ranged level to be absurdly high
3. Your arrows will fly anywhere but where you want them.

**Expected behavior**
Arrows wouldn't lose accuracy.

**Environment**
- [x] Server
- [ ] Client
- [ ] Singleplayer
- [ ] Lan Server

**Comment by SilverAndro** [comment]
Ahhh I bet I know what causes this, lmao

Will fix later

**Comment by HyperSoop** [comment]
> Ahhh I bet I know what causes this, lmao
> 
> Will fix later

could you please make sure it works with the archer class from origins classes

**Comment by SilverAndro** [comment]
I sadly dont have the time to test that as college is approaching my time is getting more and more limited

**Comment by SilverAndro** [comment]
Fix in 4.3.17
