### ISSUE TITLE
[Feature Request] Leveling progress bar

### ISSUE THREAD

**Issue by elhertz** [SilverAndro/RPGStats#118]
I was checking the #showcase channel in the Fabric-Server Side Development's discord server and found a video posted by @Martmists#3740 (discord account) showcasing a cool idea that I would like to see in RPGStats.

https://user-images.githubusercontent.com/13700335/188290688-f63b078d-d352-4b41-b228-f672fc0bc495.mp4

This feature should have a command to toggle it on or off based on player's preference. Also you could show the progress on different things apart from the bossbar like on the sidebar-scoreboard or action bar (the text above the inventory).

[Polydex](https://modrinth.com/mod/polydex) compatibility would be nice.
Here's also a sidebar api https://github.com/Patbox/SidebarAPI

**Comment by SilverAndro** [comment]
Well, certainly doable, although if someone else is working on a server side stats mod id rather not just, steal ideas from them

**Comment by elhertz** [comment]
> Well, certainly doable, although if someone else is working on a server side stats mod id rather not just, steal ideas from them

I don't think this could be considered "stealing an idea". I've seen lots of bukkit plugins and forge mods doing the same throughout the years since I started playing minecraft. Also that video was posted four months ago, but you do you. 
Anyway, thank you for making this mod and keeping it updated!

**Comment by SilverAndro** [comment]
> I've seen lots of bukkit plugins and forge mods doing the same throughout the years since I started playing minecraft.

Fair I suppose

I might do something similar but sticking with the text aesthetic I have so far, like with the hotbar/crosshair messages or whatever

**Comment by elhertz** [comment]
That sounds good! Thank you for taking interest in my suggestion ♥️

**Comment by SilverAndro** [comment]
Implemented in 5.0.0/quilt port (Although I think smart mode needs some tweaks eventually)
