### ISSUE TITLE
Compat with Harvest with Ease [1.19]

### ISSUE THREAD

**Issue by KiichigoUsagi** [SilverAndro/RPGStats#122]
Right-click Harvest with Harvest with Ease (https://www.curseforge.com/minecraft/mc-mods/harvest-with-ease) does not grant XP.

i looked into past issues and Simpler Harvest does not exist for 1.19.2 so that's not an option.
plus harvest with ease allows for tweaking like fortune effect when harvesting with hoes and dynamic compat with modded crops that may not be immediately compatible via config.

is there any chance for some compatibility to be added for that mod?

**Comment by SilverAndro** [comment]
Simple harvest works fine on modern versions, I can try adding support though

**Comment by Jamalam360** [comment]
Hmm, I wonder if it works with my mod, RightClickHarvest @ https://modrinth.com/right-click-harvest

**Comment by SilverAndro** [comment]
Looks like no from a quick glance, you set the block state directly

**Comment by Jamalam360** [comment]
Does RPG stats provide an API or anything for other mods 👀

**Comment by SilverAndro** [comment]
Technically yes https://github.com/SilverAndro/RPGStats/wiki/API

Its being expanded and rewritten partially with the quilt/kotlin rewrite though

**Comment by ConqAra** [comment]
the 1.18.2 versions do not have compat when i tested them.

**Comment by Nyphet** [comment]
I think it'd be better if you added a mixin to allow compatibility with Harvest with ease.  
I suggest to inject at the head or tail of `UseBlockHandler#grantExp(PlayerEntity)` and there grant the XP for your mod. This method gets called server side only and only if a crop is mature, so it should respect your criteria for giving Farming XP.

Btw I noticed that in your code you give Farming XP also for not-mature cocoa beans, is it intended? Also I noticed that no Farming XP is given for nether warts and sugar canes, is this intended too?

**Comment by Jamalam360** [comment]
I've added compatibility for RightClickHarvest as well now, I used rpgstats own behaviour of not giving xp for sugar cane etc., did think it was weird though

**Comment by Nyphet** [comment]
@SilverAndro any update on this?

**Comment by SilverAndro** [comment]
Yeah uh, I have no laptop atm!

Will tackle this eventually

**Comment by TheeMrCheeky** [comment]
Has this been addressed yet?

**Comment by SilverAndro** [comment]
Was busy with 5.0.0 so no

Ill look into it later

**Comment by TheeMrCheeky** [comment]
all good. was just checking! :) ty

**Comment by SilverAndro** [comment]
added in 5.0.2
