### ISSUE TITLE
Every block gives mining xp

### ISSUE THREAD

**Issue by Soochaehwa** [SilverAndro/RPGStats#126]
**Describe the bug**
Every block gives mining xp

**To Reproduce**
1. break the block

**Expected behavior**
Only ore blocks should give mining experience

**Screenshots and Logs**
![2022-11-24_18 32 11](https://user-images.githubusercontent.com/43947445/203748527-62022f9c-0824-4c9b-a4dc-57c02a9e62cc.png)
![2022-11-24_18 32 18](https://user-images.githubusercontent.com/43947445/203748543-69978f4c-5820-480d-9f72-e8b281eb1d2c.png)
![2022-11-24_18 32 25](https://user-images.githubusercontent.com/43947445/203748548-07531aa3-4be4-49c7-9ff8-ce9e72b767e7.png)
![2022-11-24_18 32 41](https://user-images.githubusercontent.com/43947445/203748551-f3fa9246-a8bc-48eb-b19c-52f6aac737e6.png)
![2022-11-24_18 32 45](https://user-images.githubusercontent.com/43947445/203748556-8a4a5d11-0400-4aec-a03c-b3e46b5965ae.png)

**Environment**
- [x] Server
- [ ] Client
- [x] Singleplayer
- [ ] Lan Server

**Mod list**
Provide your mod list here if possible.

**Comment by SilverAndro** [comment]
Hmm I think I know what the issue is here, I don't have a laptop but I'll see if I can get someone else to build a fix
