### ISSUE TITLE
Reach Increase Stat in Old Releases

### ISSUE THREAD

**Issue by Pascal204** [SilverAndro/RPGStats#135]
Did this mod have a reach increase stat before? If so, which version has it and why was it removed?
Thanks.

**Comment by SilverAndro** [comment]
i dont recall this mod ever having a reach stat, if it did it was a long long time ago. mind sharing why you asked?

**Comment by Pascal204** [comment]
I remember playing in 1.16.5 or before and there was a skill that increases your reach by 1 or so (I might be wrong), I downloaded this mod because of that back then. I think it's a really good feature.
