### ISSUE TITLE
Does this mod stil work on Fabric with version 1.20.1 of minecraft?

### ISSUE THREAD

**Issue by PassyFox** [SilverAndro/RPGStats#137]
I noticed you switched to Quilt, but does that mean this mod does not load in fabric anymore or do i need additional mods to make it work aggain?

**Comment by SilverAndro** [comment]
wont load on fabric, but fabric mods should load on quilt, so up to you

**Comment by PassyFox** [comment]
hmmmm due to Quilt being still in beta it would be very hard to have all the mods we use on the server transmission to Quilt. while i do understand that Quilt is maybe a better solution for mod makers, can i request a kind update of the 1.19.2 version 4.5 to be compatible with minecraft 1.20.1. No need to rework everything or add the new features but just make it so the last version for Fabric can work on the new 1.20.1 minecraft version.

**Comment by SilverAndro** [comment]
unfortunately i just really do not have the energy to maintain 2 versions at once, sorry

the fabric version is especially tedious as its much less abstracted and rougher to update (part of why i rewrote it on quilt)

**Comment by elhertz** [comment]
We have mods that don't work on Quilt and now we have mods that don't support fabric. I understand your reasons but in my honest opinion I think it's too early to adopt an only-support-Quilt approach with modding.
It's your mod, of course, so you do you.
